Controllers/EpsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICBF_3.Models;

namespace ICBF_3.Controllers
{
    public class EpsController : Controller
    {
        private readonly IcbfContext _context;

        public EpsController(IcbfContext context)
        {
            _context = context;
        }

        // GET: Eps
        public async Task<IActionResult> Index()
        {
            return View(await _context.Eps.ToListAsync());
        }

        // GET: Eps/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ep = await _context.Eps
                .FirstOrDefaultAsync(m => m.PkIdEps == id);
            if (ep == null)
            {
                return NotFound();
            }

            return View(ep);
        }

        // GET: Eps/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Eps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PkIdEps,Nit,Nombre,CentroMedico,Direccion,Telefono")] Ep ep)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ep);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ep);
        }

        // GET: Eps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ep = await _context.Eps.FindAsync(id);
            if (ep == null)
            {
                return NotFound();
            }
            return View(ep);
        }

        // POST: Eps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PkIdEps,Nit,Nombre,CentroMedico,Direccion,Telefono")] Ep ep)
        {
            if (id != ep.PkIdEps)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ep);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EpExists(ep.PkIdEps))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ep);
        }

        // GET: Eps/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ep = await _context.Eps
                .FirstOrDefaultAsync(m => m.PkIdEps == id);
            if (ep == null)
            {
                return NotFound();
            }

            return View(ep);
        }

        // POST: Eps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ep = await _context.Eps.FindAsync(id);
            if (ep != null)
            {
                _context.Eps.Remove(ep);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EpExists(int id)
        {
            return _context.Eps.Any(e => e.PkIdEps == id);
        }
    }
}

Controllers/NinoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICBF_3.Models;

namespace ICBF_3.Controllers
{
    public class NinoesController : Controller
    {
        private readonly IcbfContext _context;

        public NinoesController(IcbfContext context)
        {
            _context = context;
        }

        // GET: Ninoes
        public async Task<IActionResult> Index()
        {
            var icbfContext = _context.Ninos.Include(n => n.FkIdEpsNavigation).Include(n => n.FkIdJardinNavigation).Include(n => n.FkIdUsuarioNavigation);
            return View(await icbfContext.ToListAsync());
        }

        // GET: Ninoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nino = await _context.Ninos
                .Include(n => n.FkIdEpsNavigation)
                .Include(n => n.FkIdJardinNavigation)
                .Include(n => n.FkIdUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.PkIdNino == id);
            if (nino == null)
            {
                return NotFound();
            }

            return View(nino);
        }

        // GET: Ninoes/Create
        public IActionResult Create()
        {
            ViewData["FkIdEps"] = new SelectList(_context.Eps, "PkIdEps", "nombre");
            ViewData["FkIdJardin"] = new SelectList(_context.Jardines, "PkIdJardin", "PkIdJardin");
            ViewData["FkIdUsuario"] = new SelectList(_context.Usuarios, "PkIdUsuario", "PkIdUsuario");
            return View();
        }

        // POST: Ninoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PkIdNino,Niup,TipoSangre,CiudadNacimiento,FkIdEps,FkIdJardin,FkIdUsuario")] Nino nino)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nino);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkIdEps"] = new SelectList(_context.Eps, "PkIdEps", "nombre", nino.FkIdEps);
            ViewData["FkIdJardin"] = new SelectList(_context.Jardines, "PkIdJardin", "PkIdJardin", nino.FkIdJardin);
            ViewData["FkIdUsuario"] = new SelectList(_context.Usuarios, "PkIdUsuario", "PkIdUsuario", nino.FkIdUsuario);
            return View(nino);
        }

        // GET: Ninoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nino = await _context.Ninos.FindAsync(id);
            if (nino == null)
            {
                return NotFound();
            }
            ViewData["FkIdEps"] = new SelectList(_context.Eps, "PkIdEps", "PkIdEps", nino.FkIdEps);
            ViewData["FkIdJardin"] = new SelectList(_context.Jardines, "PkIdJardin", "PkIdJardin", nino.FkIdJardin);
            ViewData["FkIdUsuario"] = new SelectList(_context.Usuarios, "PkIdUsuario", "PkIdUsuario", nino.FkIdUsuario);
            return View(nino);
        }

        // POST: Ninoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PkIdNino,Niup,TipoSangre,CiudadNacimiento,FkIdEps,FkIdJardin,FkIdUsuario")] Nino nino)
        {
            if (id != nino.PkIdNino)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nino);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NinoExists(nino.PkIdNino))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkIdEps"] = new SelectList(_context.Eps, "PkIdEps", "PkIdEps", nino.FkIdEps);
            ViewData["FkIdJardin"] = new SelectList(_context.Jardines, "PkIdJardin", "PkIdJardin", nino.FkIdJardin);
            ViewData["FkIdUsuario"] = new SelectList(_context.Usuarios, "PkIdUsuario", "PkIdUsuario", nino.FkIdUsuario);
            return View(nino);
        }

        // GET: Ninoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nino = await _context.Ninos
                .Include(n => n.FkIdEpsNavigation)
                .Include(n => n.FkIdJardinNavigation)
                .Include(n => n.FkIdUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.PkIdNino == id);
            if (nino == null)
            {
                return NotFound();
            }

            return View(nino);
        }

        // POST: Ninoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nino = await _context.Ninos.FindAsync(id);
            if (nino != null)
            {
                _context.Ninos.Remove(nino);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NinoExists(int id)
        {
            return _context.Ninos.Any(e => e.PkIdNino == id);
        }
    }
}

Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICBF_3.Models;

namespace ICBF_3.Controllers
{
    public class RolesController : Controller
    {
        private readonly IcbfContext _context;

        public RolesController(IcbfContext context)
        {
            _context = context;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.PkIdRol == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PkIdRol,Tipo")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PkIdRol,Tipo")] Role role)
        {
            if (id != role.PkIdRol)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.PkIdRol))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.PkIdRol == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            if (role != null)
            {
                _context.Roles.Remove(role);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.PkIdRol == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ICBF_3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ICBF_3.styles.css" asp-append-version="true" />
    <style>
        .navbar-brand {
            font-weight: bold;
            font-size: 1.5rem;
        }

        .navbar-nav .nav-link {
            font-weight: 500;
            font-size: 1.1rem;
        }

        .navbar-toggler {
            border: none;
        }

        .navbar-collapse {
            justify-content: center;
        }

        .navbar-nav {
            margin-left: auto;
        }

            .navbar-nav .nav-item {
                margin-right: 10px;
            }

            .navbar-nav .nav-link {
                color: #343a40; /* Cambia el color de los enlaces */
            }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ICBF_3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Asistencias" asp-action="Index">Asistencias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Ninoes" asp-action="Index">Niños</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="AvancesAcademicoes" asp-action="Index">Avances Académicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Eps" asp-action="Index">Eps</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Jardines" asp-action="Index">Jardines</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="TipoDocs" asp-action="Index">TipoDocs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ICBF_3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>